/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.daos;


import com.api.jooq.tables.CoAlumno;
import com.api.jooq.tables.records.CoAlumnoRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoAlumnoDao extends DAOImpl<CoAlumnoRecord, com.api.jooq.tables.pojos.CoAlumno, Integer> {

    /**
     * Create a new CoAlumnoDao without any configuration
     */
    public CoAlumnoDao() {
        super(CoAlumno.CO_ALUMNO, com.api.jooq.tables.pojos.CoAlumno.class);
    }

    /**
     * Create a new CoAlumnoDao with an attached configuration
     */
    public CoAlumnoDao(Configuration configuration) {
        super(CoAlumno.CO_ALUMNO, com.api.jooq.tables.pojos.CoAlumno.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.api.jooq.tables.pojos.CoAlumno object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchById(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.api.jooq.tables.pojos.CoAlumno fetchOneById(Integer value) {
        return fetchOne(CoAlumno.CO_ALUMNO.ID, value);
    }

    /**
     * Fetch records that have <code>co_sucursal IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByCoSucursal(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.CO_SUCURSAL, values);
    }

    /**
     * Fetch records that have <code>co_grupo IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByCoGrupo(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.CO_GRUPO, values);
    }

    /**
     * Fetch records that have <code>co_padre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByCoPadre(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.CO_PADRE, values);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByNombre(String... values) {
        return fetch(CoAlumno.CO_ALUMNO.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>fecha_nacimiento IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByFechaNacimiento(Date... values) {
        return fetch(CoAlumno.CO_ALUMNO.FECHA_NACIMIENTO, values);
    }

    /**
     * Fetch records that have <code>alergias IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByAlergias(String... values) {
        return fetch(CoAlumno.CO_ALUMNO.ALERGIAS, values);
    }

    /**
     * Fetch records that have <code>nota IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByNota(String... values) {
        return fetch(CoAlumno.CO_ALUMNO.NOTA, values);
    }

    /**
     * Fetch records that have <code>hora_salida IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByHoraSalida(Time... values) {
        return fetch(CoAlumno.CO_ALUMNO.HORA_SALIDA, values);
    }

    /**
     * Fetch records that have <code>costo_inscripcion IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByCostoInscripcion(BigDecimal... values) {
        return fetch(CoAlumno.CO_ALUMNO.COSTO_INSCRIPCION, values);
    }

    /**
     * Fetch records that have <code>costo_colegiatura IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByCostoColegiatura(BigDecimal... values) {
        return fetch(CoAlumno.CO_ALUMNO.COSTO_COLEGIATURA, values);
    }

    /**
     * Fetch records that have <code>minutos_gracia IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByMinutosGracia(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.MINUTOS_GRACIA, values);
    }

    /**
     * Fetch records that have <code>foto IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByFoto(String... values) {
        return fetch(CoAlumno.CO_ALUMNO.FOTO, values);
    }

    /**
     * Fetch records that have <code>fecha_reinscripcion IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByFechaReinscripcion(Date... values) {
        return fetch(CoAlumno.CO_ALUMNO.FECHA_REINSCRIPCION, values);
    }

    /**
     * Fetch records that have <code>fecha_genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByFechaGenero(Timestamp... values) {
        return fetch(CoAlumno.CO_ALUMNO.FECHA_GENERO, values);
    }

    /**
     * Fetch records that have <code>fecha_modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByFechaModifico(Timestamp... values) {
        return fetch(CoAlumno.CO_ALUMNO.FECHA_MODIFICO, values);
    }

    /**
     * Fetch records that have <code>genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByGenero(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.GENERO, values);
    }

    /**
     * Fetch records that have <code>modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByModifico(Integer... values) {
        return fetch(CoAlumno.CO_ALUMNO.MODIFICO, values);
    }

    /**
     * Fetch records that have <code>eliminado IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoAlumno> fetchByEliminado(Boolean... values) {
        return fetch(CoAlumno.CO_ALUMNO.ELIMINADO, values);
    }
}
