/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.daos;


import com.api.jooq.tables.CoGrupo;
import com.api.jooq.tables.records.CoGrupoRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoGrupoDao extends DAOImpl<CoGrupoRecord, com.api.jooq.tables.pojos.CoGrupo, Integer> {

    /**
     * Create a new CoGrupoDao without any configuration
     */
    public CoGrupoDao() {
        super(CoGrupo.CO_GRUPO, com.api.jooq.tables.pojos.CoGrupo.class);
    }

    /**
     * Create a new CoGrupoDao with an attached configuration
     */
    public CoGrupoDao(Configuration configuration) {
        super(CoGrupo.CO_GRUPO, com.api.jooq.tables.pojos.CoGrupo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.api.jooq.tables.pojos.CoGrupo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchById(Integer... values) {
        return fetch(CoGrupo.CO_GRUPO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.api.jooq.tables.pojos.CoGrupo fetchOneById(Integer value) {
        return fetchOne(CoGrupo.CO_GRUPO.ID, value);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByNombre(String... values) {
        return fetch(CoGrupo.CO_GRUPO.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>fecha_genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByFechaGenero(Timestamp... values) {
        return fetch(CoGrupo.CO_GRUPO.FECHA_GENERO, values);
    }

    /**
     * Fetch records that have <code>fecha_modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByFechaModifico(Timestamp... values) {
        return fetch(CoGrupo.CO_GRUPO.FECHA_MODIFICO, values);
    }

    /**
     * Fetch records that have <code>genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByGenero(Integer... values) {
        return fetch(CoGrupo.CO_GRUPO.GENERO, values);
    }

    /**
     * Fetch records that have <code>modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByModifico(Integer... values) {
        return fetch(CoGrupo.CO_GRUPO.MODIFICO, values);
    }

    /**
     * Fetch records that have <code>eliminado IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoGrupo> fetchByEliminado(Boolean... values) {
        return fetch(CoGrupo.CO_GRUPO.ELIMINADO, values);
    }
}
