/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.daos;


import com.api.jooq.tables.CoPadre;
import com.api.jooq.tables.records.CoPadreRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoPadreDao extends DAOImpl<CoPadreRecord, com.api.jooq.tables.pojos.CoPadre, Integer> {

    /**
     * Create a new CoPadreDao without any configuration
     */
    public CoPadreDao() {
        super(CoPadre.CO_PADRE, com.api.jooq.tables.pojos.CoPadre.class);
    }

    /**
     * Create a new CoPadreDao with an attached configuration
     */
    public CoPadreDao(Configuration configuration) {
        super(CoPadre.CO_PADRE, com.api.jooq.tables.pojos.CoPadre.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.api.jooq.tables.pojos.CoPadre object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchById(Integer... values) {
        return fetch(CoPadre.CO_PADRE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.api.jooq.tables.pojos.CoPadre fetchOneById(Integer value) {
        return fetchOne(CoPadre.CO_PADRE.ID, value);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByNombre(String... values) {
        return fetch(CoPadre.CO_PADRE.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>correo IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByCorreo(String... values) {
        return fetch(CoPadre.CO_PADRE.CORREO, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByPassword(String... values) {
        return fetch(CoPadre.CO_PADRE.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>telefono IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByTelefono(String... values) {
        return fetch(CoPadre.CO_PADRE.TELEFONO, values);
    }

    /**
     * Fetch records that have <code>fecha_genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByFechaGenero(Timestamp... values) {
        return fetch(CoPadre.CO_PADRE.FECHA_GENERO, values);
    }

    /**
     * Fetch records that have <code>fecha_modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByFechaModifico(Timestamp... values) {
        return fetch(CoPadre.CO_PADRE.FECHA_MODIFICO, values);
    }

    /**
     * Fetch records that have <code>genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByGenero(Integer... values) {
        return fetch(CoPadre.CO_PADRE.GENERO, values);
    }

    /**
     * Fetch records that have <code>modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByModifico(Integer... values) {
        return fetch(CoPadre.CO_PADRE.MODIFICO, values);
    }

    /**
     * Fetch records that have <code>eliminado IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoPadre> fetchByEliminado(Boolean... values) {
        return fetch(CoPadre.CO_PADRE.ELIMINADO, values);
    }
}
