/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.daos;


import com.api.jooq.tables.CoSucursal;
import com.api.jooq.tables.records.CoSucursalRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoSucursalDao extends DAOImpl<CoSucursalRecord, com.api.jooq.tables.pojos.CoSucursal, Integer> {

    /**
     * Create a new CoSucursalDao without any configuration
     */
    public CoSucursalDao() {
        super(CoSucursal.CO_SUCURSAL, com.api.jooq.tables.pojos.CoSucursal.class);
    }

    /**
     * Create a new CoSucursalDao with an attached configuration
     */
    public CoSucursalDao(Configuration configuration) {
        super(CoSucursal.CO_SUCURSAL, com.api.jooq.tables.pojos.CoSucursal.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.api.jooq.tables.pojos.CoSucursal object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchById(Integer... values) {
        return fetch(CoSucursal.CO_SUCURSAL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.api.jooq.tables.pojos.CoSucursal fetchOneById(Integer value) {
        return fetchOne(CoSucursal.CO_SUCURSAL.ID, value);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByNombre(String... values) {
        return fetch(CoSucursal.CO_SUCURSAL.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>direccion IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByDireccion(String... values) {
        return fetch(CoSucursal.CO_SUCURSAL.DIRECCION, values);
    }

    /**
     * Fetch records that have <code>fecha_genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByFechaGenero(Timestamp... values) {
        return fetch(CoSucursal.CO_SUCURSAL.FECHA_GENERO, values);
    }

    /**
     * Fetch records that have <code>fecha_modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByFechaModifico(Timestamp... values) {
        return fetch(CoSucursal.CO_SUCURSAL.FECHA_MODIFICO, values);
    }

    /**
     * Fetch records that have <code>genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByGenero(Integer... values) {
        return fetch(CoSucursal.CO_SUCURSAL.GENERO, values);
    }

    /**
     * Fetch records that have <code>modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByModifico(Integer... values) {
        return fetch(CoSucursal.CO_SUCURSAL.MODIFICO, values);
    }

    /**
     * Fetch records that have <code>eliminado IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.CoSucursal> fetchByEliminado(Boolean... values) {
        return fetch(CoSucursal.CO_SUCURSAL.ELIMINADO, values);
    }
}
