/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.daos;


import com.api.jooq.tables.Usuario;
import com.api.jooq.tables.records.UsuarioRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioDao extends DAOImpl<UsuarioRecord, com.api.jooq.tables.pojos.Usuario, Integer> {

    /**
     * Create a new UsuarioDao without any configuration
     */
    public UsuarioDao() {
        super(Usuario.USUARIO, com.api.jooq.tables.pojos.Usuario.class);
    }

    /**
     * Create a new UsuarioDao with an attached configuration
     */
    public UsuarioDao(Configuration configuration) {
        super(Usuario.USUARIO, com.api.jooq.tables.pojos.Usuario.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.api.jooq.tables.pojos.Usuario object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchById(Integer... values) {
        return fetch(Usuario.USUARIO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.api.jooq.tables.pojos.Usuario fetchOneById(Integer value) {
        return fetchOne(Usuario.USUARIO.ID, value);
    }

    /**
     * Fetch records that have <code>nombre IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByNombre(String... values) {
        return fetch(Usuario.USUARIO.NOMBRE, values);
    }

    /**
     * Fetch records that have <code>correo IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByCorreo(String... values) {
        return fetch(Usuario.USUARIO.CORREO, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByPassword(String... values) {
        return fetch(Usuario.USUARIO.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>fecha_genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByFechaGenero(Timestamp... values) {
        return fetch(Usuario.USUARIO.FECHA_GENERO, values);
    }

    /**
     * Fetch records that have <code>fecha_modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByFechaModifico(Timestamp... values) {
        return fetch(Usuario.USUARIO.FECHA_MODIFICO, values);
    }

    /**
     * Fetch records that have <code>genero IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByGenero(Integer... values) {
        return fetch(Usuario.USUARIO.GENERO, values);
    }

    /**
     * Fetch records that have <code>modifico IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByModifico(Integer... values) {
        return fetch(Usuario.USUARIO.MODIFICO, values);
    }

    /**
     * Fetch records that have <code>eliminado IN (values)</code>
     */
    public List<com.api.jooq.tables.pojos.Usuario> fetchByEliminado(Boolean... values) {
        return fetch(Usuario.USUARIO.ELIMINADO, values);
    }
}
