/*
 * This file is generated by jOOQ.
 */
package com.api.jooq;


import com.api.jooq.tables.CoAlumno;
import com.api.jooq.tables.CoGrupo;
import com.api.jooq.tables.CoPadre;
import com.api.jooq.tables.CoSucursal;
import com.api.jooq.tables.Usuario;
import com.api.jooq.tables.records.CoAlumnoRecord;
import com.api.jooq.tables.records.CoGrupoRecord;
import com.api.jooq.tables.records.CoPadreRecord;
import com.api.jooq.tables.records.CoSucursalRecord;
import com.api.jooq.tables.records.UsuarioRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CoAlumnoRecord, Integer> IDENTITY_CO_ALUMNO = Identities0.IDENTITY_CO_ALUMNO;
    public static final Identity<CoGrupoRecord, Integer> IDENTITY_CO_GRUPO = Identities0.IDENTITY_CO_GRUPO;
    public static final Identity<CoPadreRecord, Integer> IDENTITY_CO_PADRE = Identities0.IDENTITY_CO_PADRE;
    public static final Identity<CoSucursalRecord, Integer> IDENTITY_CO_SUCURSAL = Identities0.IDENTITY_CO_SUCURSAL;
    public static final Identity<UsuarioRecord, Integer> IDENTITY_USUARIO = Identities0.IDENTITY_USUARIO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CoAlumnoRecord> CO_ALUMNO_PKEY = UniqueKeys0.CO_ALUMNO_PKEY;
    public static final UniqueKey<CoGrupoRecord> CO_GRUPO_PKEY = UniqueKeys0.CO_GRUPO_PKEY;
    public static final UniqueKey<CoPadreRecord> CO_PADRE_PKEY = UniqueKeys0.CO_PADRE_PKEY;
    public static final UniqueKey<CoSucursalRecord> CO_SUCURSAL_PKEY = UniqueKeys0.CO_SUCURSAL_PKEY;
    public static final UniqueKey<UsuarioRecord> USUARIO_PKEY = UniqueKeys0.USUARIO_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CoAlumnoRecord, Integer> IDENTITY_CO_ALUMNO = Internal.createIdentity(CoAlumno.CO_ALUMNO, CoAlumno.CO_ALUMNO.ID);
        public static Identity<CoGrupoRecord, Integer> IDENTITY_CO_GRUPO = Internal.createIdentity(CoGrupo.CO_GRUPO, CoGrupo.CO_GRUPO.ID);
        public static Identity<CoPadreRecord, Integer> IDENTITY_CO_PADRE = Internal.createIdentity(CoPadre.CO_PADRE, CoPadre.CO_PADRE.ID);
        public static Identity<CoSucursalRecord, Integer> IDENTITY_CO_SUCURSAL = Internal.createIdentity(CoSucursal.CO_SUCURSAL, CoSucursal.CO_SUCURSAL.ID);
        public static Identity<UsuarioRecord, Integer> IDENTITY_USUARIO = Internal.createIdentity(Usuario.USUARIO, Usuario.USUARIO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CoAlumnoRecord> CO_ALUMNO_PKEY = Internal.createUniqueKey(CoAlumno.CO_ALUMNO, "co_alumno_pkey", CoAlumno.CO_ALUMNO.ID);
        public static final UniqueKey<CoGrupoRecord> CO_GRUPO_PKEY = Internal.createUniqueKey(CoGrupo.CO_GRUPO, "co_grupo_pkey", CoGrupo.CO_GRUPO.ID);
        public static final UniqueKey<CoPadreRecord> CO_PADRE_PKEY = Internal.createUniqueKey(CoPadre.CO_PADRE, "co_padre_pkey", CoPadre.CO_PADRE.ID);
        public static final UniqueKey<CoSucursalRecord> CO_SUCURSAL_PKEY = Internal.createUniqueKey(CoSucursal.CO_SUCURSAL, "co_sucursal_pkey", CoSucursal.CO_SUCURSAL.ID);
        public static final UniqueKey<UsuarioRecord> USUARIO_PKEY = Internal.createUniqueKey(Usuario.USUARIO, "usuario_pkey", Usuario.USUARIO.ID);
    }
}
