/*
 * This file is generated by jOOQ.
 */
package com.api.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.co_alumno_id_seq</code>
     */
    public static final Sequence<Integer> CO_ALUMNO_ID_SEQ = new SequenceImpl<Integer>("co_alumno_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.co_grupo_id_seq</code>
     */
    public static final Sequence<Integer> CO_GRUPO_ID_SEQ = new SequenceImpl<Integer>("co_grupo_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.co_padre_id_seq</code>
     */
    public static final Sequence<Integer> CO_PADRE_ID_SEQ = new SequenceImpl<Integer>("co_padre_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.co_sucursal_id_seq</code>
     */
    public static final Sequence<Integer> CO_SUCURSAL_ID_SEQ = new SequenceImpl<Integer>("co_sucursal_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.usuario_id_seq</code>
     */
    public static final Sequence<Integer> USUARIO_ID_SEQ = new SequenceImpl<Integer>("usuario_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
