/*
 * This file is generated by jOOQ.
 */
package com.api.jooq;


import com.api.jooq.tables.CoAlumno;
import com.api.jooq.tables.CoGrupo;
import com.api.jooq.tables.CoPadre;
import com.api.jooq.tables.CoSucursal;
import com.api.jooq.tables.Usuario;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.co_alumno</code>.
     */
    public static final CoAlumno CO_ALUMNO = com.api.jooq.tables.CoAlumno.CO_ALUMNO;

    /**
     * The table <code>public.co_grupo</code>.
     */
    public static final CoGrupo CO_GRUPO = com.api.jooq.tables.CoGrupo.CO_GRUPO;

    /**
     * The table <code>public.co_padre</code>.
     */
    public static final CoPadre CO_PADRE = com.api.jooq.tables.CoPadre.CO_PADRE;

    /**
     * The table <code>public.co_sucursal</code>.
     */
    public static final CoSucursal CO_SUCURSAL = com.api.jooq.tables.CoSucursal.CO_SUCURSAL;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = com.api.jooq.tables.Usuario.USUARIO;
}
