/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.records;


import com.api.jooq.tables.CoAlumno;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoAlumnoRecord extends UpdatableRecordImpl<CoAlumnoRecord> implements Record19<Integer, Integer, Integer, Integer, String, Date, String, String, Time, BigDecimal, BigDecimal, Integer, String, Date, Timestamp, Timestamp, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1010660347;

    /**
     * Setter for <code>public.co_alumno.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.co_alumno.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.co_alumno.co_sucursal</code>.
     */
    public void setCoSucursal(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.co_alumno.co_sucursal</code>.
     */
    public Integer getCoSucursal() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.co_alumno.co_grupo</code>.
     */
    public void setCoGrupo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.co_alumno.co_grupo</code>.
     */
    public Integer getCoGrupo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.co_alumno.co_padre</code>.
     */
    public void setCoPadre(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.co_alumno.co_padre</code>.
     */
    public Integer getCoPadre() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.co_alumno.nombre</code>.
     */
    public void setNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.co_alumno.nombre</code>.
     */
    public String getNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.co_alumno.fecha_nacimiento</code>.
     */
    public void setFechaNacimiento(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.co_alumno.fecha_nacimiento</code>.
     */
    public Date getFechaNacimiento() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.co_alumno.alergias</code>.
     */
    public void setAlergias(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.co_alumno.alergias</code>.
     */
    public String getAlergias() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.co_alumno.nota</code>.
     */
    public void setNota(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.co_alumno.nota</code>.
     */
    public String getNota() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.co_alumno.hora_salida</code>.
     */
    public void setHoraSalida(Time value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.co_alumno.hora_salida</code>.
     */
    public Time getHoraSalida() {
        return (Time) get(8);
    }

    /**
     * Setter for <code>public.co_alumno.costo_inscripcion</code>.
     */
    public void setCostoInscripcion(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.co_alumno.costo_inscripcion</code>.
     */
    public BigDecimal getCostoInscripcion() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.co_alumno.costo_colegiatura</code>.
     */
    public void setCostoColegiatura(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.co_alumno.costo_colegiatura</code>.
     */
    public BigDecimal getCostoColegiatura() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.co_alumno.minutos_gracia</code>.
     */
    public void setMinutosGracia(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.co_alumno.minutos_gracia</code>.
     */
    public Integer getMinutosGracia() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.co_alumno.foto</code>.
     */
    public void setFoto(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.co_alumno.foto</code>.
     */
    public String getFoto() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.co_alumno.fecha_reinscripcion</code>.
     */
    public void setFechaReinscripcion(Date value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.co_alumno.fecha_reinscripcion</code>.
     */
    public Date getFechaReinscripcion() {
        return (Date) get(13);
    }

    /**
     * Setter for <code>public.co_alumno.fecha_genero</code>.
     */
    public void setFechaGenero(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.co_alumno.fecha_genero</code>.
     */
    public Timestamp getFechaGenero() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>public.co_alumno.fecha_modifico</code>.
     */
    public void setFechaModifico(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.co_alumno.fecha_modifico</code>.
     */
    public Timestamp getFechaModifico() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>public.co_alumno.genero</code>.
     */
    public void setGenero(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.co_alumno.genero</code>.
     */
    public Integer getGenero() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.co_alumno.modifico</code>.
     */
    public void setModifico(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.co_alumno.modifico</code>.
     */
    public Integer getModifico() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.co_alumno.eliminado</code>.
     */
    public void setEliminado(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.co_alumno.eliminado</code>.
     */
    public Boolean getEliminado() {
        return (Boolean) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, Integer, Integer, Integer, String, Date, String, String, Time, BigDecimal, BigDecimal, Integer, String, Date, Timestamp, Timestamp, Integer, Integer, Boolean> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, Integer, Integer, Integer, String, Date, String, String, Time, BigDecimal, BigDecimal, Integer, String, Date, Timestamp, Timestamp, Integer, Integer, Boolean> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CoAlumno.CO_ALUMNO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CoAlumno.CO_ALUMNO.CO_SUCURSAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CoAlumno.CO_ALUMNO.CO_GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CoAlumno.CO_ALUMNO.CO_PADRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CoAlumno.CO_ALUMNO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return CoAlumno.CO_ALUMNO.FECHA_NACIMIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CoAlumno.CO_ALUMNO.ALERGIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CoAlumno.CO_ALUMNO.NOTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field9() {
        return CoAlumno.CO_ALUMNO.HORA_SALIDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return CoAlumno.CO_ALUMNO.COSTO_INSCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return CoAlumno.CO_ALUMNO.COSTO_COLEGIATURA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return CoAlumno.CO_ALUMNO.MINUTOS_GRACIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CoAlumno.CO_ALUMNO.FOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field14() {
        return CoAlumno.CO_ALUMNO.FECHA_REINSCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return CoAlumno.CO_ALUMNO.FECHA_GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return CoAlumno.CO_ALUMNO.FECHA_MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return CoAlumno.CO_ALUMNO.GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return CoAlumno.CO_ALUMNO.MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field19() {
        return CoAlumno.CO_ALUMNO.ELIMINADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCoSucursal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCoGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCoPadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAlergias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNota();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component9() {
        return getHoraSalida();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getCostoInscripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getCostoColegiatura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getMinutosGracia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component14() {
        return getFechaReinscripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component19() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCoSucursal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCoGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCoPadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAlergias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNota();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value9() {
        return getHoraSalida();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getCostoInscripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getCostoColegiatura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getMinutosGracia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value14() {
        return getFechaReinscripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value19() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value2(Integer value) {
        setCoSucursal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value3(Integer value) {
        setCoGrupo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value4(Integer value) {
        setCoPadre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value5(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value6(Date value) {
        setFechaNacimiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value7(String value) {
        setAlergias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value8(String value) {
        setNota(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value9(Time value) {
        setHoraSalida(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value10(BigDecimal value) {
        setCostoInscripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value11(BigDecimal value) {
        setCostoColegiatura(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value12(Integer value) {
        setMinutosGracia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value13(String value) {
        setFoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value14(Date value) {
        setFechaReinscripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value15(Timestamp value) {
        setFechaGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value16(Timestamp value) {
        setFechaModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value17(Integer value) {
        setGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value18(Integer value) {
        setModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord value19(Boolean value) {
        setEliminado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoAlumnoRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Date value6, String value7, String value8, Time value9, BigDecimal value10, BigDecimal value11, Integer value12, String value13, Date value14, Timestamp value15, Timestamp value16, Integer value17, Integer value18, Boolean value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoAlumnoRecord
     */
    public CoAlumnoRecord() {
        super(CoAlumno.CO_ALUMNO);
    }

    /**
     * Create a detached, initialised CoAlumnoRecord
     */
    public CoAlumnoRecord(Integer id, Integer coSucursal, Integer coGrupo, Integer coPadre, String nombre, Date fechaNacimiento, String alergias, String nota, Time horaSalida, BigDecimal costoInscripcion, BigDecimal costoColegiatura, Integer minutosGracia, String foto, Date fechaReinscripcion, Timestamp fechaGenero, Timestamp fechaModifico, Integer genero, Integer modifico, Boolean eliminado) {
        super(CoAlumno.CO_ALUMNO);

        set(0, id);
        set(1, coSucursal);
        set(2, coGrupo);
        set(3, coPadre);
        set(4, nombre);
        set(5, fechaNacimiento);
        set(6, alergias);
        set(7, nota);
        set(8, horaSalida);
        set(9, costoInscripcion);
        set(10, costoColegiatura);
        set(11, minutosGracia);
        set(12, foto);
        set(13, fechaReinscripcion);
        set(14, fechaGenero);
        set(15, fechaModifico);
        set(16, genero);
        set(17, modifico);
        set(18, eliminado);
    }
}
