/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.records;


import com.api.jooq.tables.CoPadre;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoPadreRecord extends UpdatableRecordImpl<CoPadreRecord> implements Record10<Integer, String, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> {

    private static final long serialVersionUID = -1934293886;

    /**
     * Setter for <code>public.co_padre.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.co_padre.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.co_padre.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.co_padre.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.co_padre.correo</code>.
     */
    public void setCorreo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.co_padre.correo</code>.
     */
    public String getCorreo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.co_padre.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.co_padre.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.co_padre.telefono</code>.
     */
    public void setTelefono(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.co_padre.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.co_padre.fecha_genero</code>.
     */
    public void setFechaGenero(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.co_padre.fecha_genero</code>.
     */
    public Timestamp getFechaGenero() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.co_padre.fecha_modifico</code>.
     */
    public void setFechaModifico(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.co_padre.fecha_modifico</code>.
     */
    public Timestamp getFechaModifico() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.co_padre.genero</code>.
     */
    public void setGenero(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.co_padre.genero</code>.
     */
    public Integer getGenero() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.co_padre.modifico</code>.
     */
    public void setModifico(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.co_padre.modifico</code>.
     */
    public Integer getModifico() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.co_padre.eliminado</code>.
     */
    public void setEliminado(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.co_padre.eliminado</code>.
     */
    public Boolean getEliminado() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CoPadre.CO_PADRE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CoPadre.CO_PADRE.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CoPadre.CO_PADRE.CORREO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CoPadre.CO_PADRE.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CoPadre.CO_PADRE.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return CoPadre.CO_PADRE.FECHA_GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return CoPadre.CO_PADRE.FECHA_MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CoPadre.CO_PADRE.GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return CoPadre.CO_PADRE.MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return CoPadre.CO_PADRE.ELIMINADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value3(String value) {
        setCorreo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value5(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value6(Timestamp value) {
        setFechaGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value7(Timestamp value) {
        setFechaModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value8(Integer value) {
        setGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value9(Integer value) {
        setModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord value10(Boolean value) {
        setEliminado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoPadreRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Integer value8, Integer value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoPadreRecord
     */
    public CoPadreRecord() {
        super(CoPadre.CO_PADRE);
    }

    /**
     * Create a detached, initialised CoPadreRecord
     */
    public CoPadreRecord(Integer id, String nombre, String correo, String password, String telefono, Timestamp fechaGenero, Timestamp fechaModifico, Integer genero, Integer modifico, Boolean eliminado) {
        super(CoPadre.CO_PADRE);

        set(0, id);
        set(1, nombre);
        set(2, correo);
        set(3, password);
        set(4, telefono);
        set(5, fechaGenero);
        set(6, fechaModifico);
        set(7, genero);
        set(8, modifico);
        set(9, eliminado);
    }
}
