/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.records;


import com.api.jooq.tables.CoSucursal;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoSucursalRecord extends UpdatableRecordImpl<CoSucursalRecord> implements Record8<Integer, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1656751309;

    /**
     * Setter for <code>public.co_sucursal.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.co_sucursal.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.co_sucursal.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.co_sucursal.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.co_sucursal.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.co_sucursal.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.co_sucursal.fecha_genero</code>.
     */
    public void setFechaGenero(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.co_sucursal.fecha_genero</code>.
     */
    public Timestamp getFechaGenero() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.co_sucursal.fecha_modifico</code>.
     */
    public void setFechaModifico(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.co_sucursal.fecha_modifico</code>.
     */
    public Timestamp getFechaModifico() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.co_sucursal.genero</code>.
     */
    public void setGenero(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.co_sucursal.genero</code>.
     */
    public Integer getGenero() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.co_sucursal.modifico</code>.
     */
    public void setModifico(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.co_sucursal.modifico</code>.
     */
    public Integer getModifico() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.co_sucursal.eliminado</code>.
     */
    public void setEliminado(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.co_sucursal.eliminado</code>.
     */
    public Boolean getEliminado() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CoSucursal.CO_SUCURSAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CoSucursal.CO_SUCURSAL.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CoSucursal.CO_SUCURSAL.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CoSucursal.CO_SUCURSAL.FECHA_GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CoSucursal.CO_SUCURSAL.FECHA_MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return CoSucursal.CO_SUCURSAL.GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CoSucursal.CO_SUCURSAL.MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return CoSucursal.CO_SUCURSAL.ELIMINADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value4(Timestamp value) {
        setFechaGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value5(Timestamp value) {
        setFechaModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value6(Integer value) {
        setGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value7(Integer value) {
        setModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord value8(Boolean value) {
        setEliminado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursalRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5, Integer value6, Integer value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoSucursalRecord
     */
    public CoSucursalRecord() {
        super(CoSucursal.CO_SUCURSAL);
    }

    /**
     * Create a detached, initialised CoSucursalRecord
     */
    public CoSucursalRecord(Integer id, String nombre, String direccion, Timestamp fechaGenero, Timestamp fechaModifico, Integer genero, Integer modifico, Boolean eliminado) {
        super(CoSucursal.CO_SUCURSAL);

        set(0, id);
        set(1, nombre);
        set(2, direccion);
        set(3, fechaGenero);
        set(4, fechaModifico);
        set(5, genero);
        set(6, modifico);
        set(7, eliminado);
    }
}
