/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables.records;


import com.api.jooq.tables.Usuario;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> implements Record9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1385415042;

    /**
     * Setter for <code>public.usuario.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usuario.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuario.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usuario.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.usuario.correo</code>.
     */
    public void setCorreo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usuario.correo</code>.
     */
    public String getCorreo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.usuario.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.usuario.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.usuario.fecha_genero</code>.
     */
    public void setFechaGenero(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.usuario.fecha_genero</code>.
     */
    public Timestamp getFechaGenero() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.usuario.fecha_modifico</code>.
     */
    public void setFechaModifico(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.usuario.fecha_modifico</code>.
     */
    public Timestamp getFechaModifico() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.usuario.genero</code>.
     */
    public void setGenero(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.usuario.genero</code>.
     */
    public Integer getGenero() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.usuario.modifico</code>.
     */
    public void setModifico(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.usuario.modifico</code>.
     */
    public Integer getModifico() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.usuario.eliminado</code>.
     */
    public void setEliminado(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.usuario.eliminado</code>.
     */
    public Boolean getEliminado() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Timestamp, Integer, Integer, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuario.USUARIO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usuario.USUARIO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuario.USUARIO.CORREO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Usuario.USUARIO.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Usuario.USUARIO.FECHA_GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Usuario.USUARIO.FECHA_MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Usuario.USUARIO.GENERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Usuario.USUARIO.MODIFICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Usuario.USUARIO.ELIMINADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFechaGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFechaModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGenero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getModifico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value3(String value) {
        setCorreo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value5(Timestamp value) {
        setFechaGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value6(Timestamp value) {
        setFechaModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value7(Integer value) {
        setGenero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value8(Integer value) {
        setModifico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value9(Boolean value) {
        setEliminado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, Integer value7, Integer value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioRecord
     */
    public UsuarioRecord() {
        super(Usuario.USUARIO);
    }

    /**
     * Create a detached, initialised UsuarioRecord
     */
    public UsuarioRecord(Integer id, String nombre, String correo, String password, Timestamp fechaGenero, Timestamp fechaModifico, Integer genero, Integer modifico, Boolean eliminado) {
        super(Usuario.USUARIO);

        set(0, id);
        set(1, nombre);
        set(2, correo);
        set(3, password);
        set(4, fechaGenero);
        set(5, fechaModifico);
        set(6, genero);
        set(7, modifico);
        set(8, eliminado);
    }
}
