/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables;


import com.api.jooq.Indexes;
import com.api.jooq.Keys;
import com.api.jooq.Public;
import com.api.jooq.tables.records.CoGrupoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoGrupo extends TableImpl<CoGrupoRecord> {

    private static final long serialVersionUID = -517900583;

    /**
     * The reference instance of <code>public.co_grupo</code>
     */
    public static final CoGrupo CO_GRUPO = new CoGrupo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoGrupoRecord> getRecordType() {
        return CoGrupoRecord.class;
    }

    /**
     * The column <code>public.co_grupo.id</code>.
     */
    public final TableField<CoGrupoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('co_grupo_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.co_grupo.nombre</code>.
     */
    public final TableField<CoGrupoRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.co_grupo.fecha_genero</code>.
     */
    public final TableField<CoGrupoRecord, Timestamp> FECHA_GENERO = createField("fecha_genero", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.co_grupo.fecha_modifico</code>.
     */
    public final TableField<CoGrupoRecord, Timestamp> FECHA_MODIFICO = createField("fecha_modifico", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.co_grupo.genero</code>.
     */
    public final TableField<CoGrupoRecord, Integer> GENERO = createField("genero", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.co_grupo.modifico</code>.
     */
    public final TableField<CoGrupoRecord, Integer> MODIFICO = createField("modifico", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.co_grupo.eliminado</code>.
     */
    public final TableField<CoGrupoRecord, Boolean> ELIMINADO = createField("eliminado", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.co_grupo</code> table reference
     */
    public CoGrupo() {
        this(DSL.name("co_grupo"), null);
    }

    /**
     * Create an aliased <code>public.co_grupo</code> table reference
     */
    public CoGrupo(String alias) {
        this(DSL.name(alias), CO_GRUPO);
    }

    /**
     * Create an aliased <code>public.co_grupo</code> table reference
     */
    public CoGrupo(Name alias) {
        this(alias, CO_GRUPO);
    }

    private CoGrupo(Name alias, Table<CoGrupoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoGrupo(Name alias, Table<CoGrupoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CoGrupo(Table<O> child, ForeignKey<O, CoGrupoRecord> key) {
        super(child, key, CO_GRUPO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CO_GRUPO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CoGrupoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CO_GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CoGrupoRecord> getPrimaryKey() {
        return Keys.CO_GRUPO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoGrupoRecord>> getKeys() {
        return Arrays.<UniqueKey<CoGrupoRecord>>asList(Keys.CO_GRUPO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoGrupo as(String alias) {
        return new CoGrupo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoGrupo as(Name alias) {
        return new CoGrupo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoGrupo rename(String name) {
        return new CoGrupo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoGrupo rename(Name name) {
        return new CoGrupo(name, null);
    }
}
