/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables;


import com.api.jooq.Indexes;
import com.api.jooq.Keys;
import com.api.jooq.Public;
import com.api.jooq.tables.records.CoSucursalRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoSucursal extends TableImpl<CoSucursalRecord> {

    private static final long serialVersionUID = -1305303172;

    /**
     * The reference instance of <code>public.co_sucursal</code>
     */
    public static final CoSucursal CO_SUCURSAL = new CoSucursal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoSucursalRecord> getRecordType() {
        return CoSucursalRecord.class;
    }

    /**
     * The column <code>public.co_sucursal.id</code>.
     */
    public final TableField<CoSucursalRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('co_sucursal_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.co_sucursal.nombre</code>.
     */
    public final TableField<CoSucursalRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.co_sucursal.direccion</code>.
     */
    public final TableField<CoSucursalRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.co_sucursal.fecha_genero</code>.
     */
    public final TableField<CoSucursalRecord, Timestamp> FECHA_GENERO = createField("fecha_genero", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.co_sucursal.fecha_modifico</code>.
     */
    public final TableField<CoSucursalRecord, Timestamp> FECHA_MODIFICO = createField("fecha_modifico", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.co_sucursal.genero</code>.
     */
    public final TableField<CoSucursalRecord, Integer> GENERO = createField("genero", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.co_sucursal.modifico</code>.
     */
    public final TableField<CoSucursalRecord, Integer> MODIFICO = createField("modifico", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.co_sucursal.eliminado</code>.
     */
    public final TableField<CoSucursalRecord, Boolean> ELIMINADO = createField("eliminado", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.co_sucursal</code> table reference
     */
    public CoSucursal() {
        this(DSL.name("co_sucursal"), null);
    }

    /**
     * Create an aliased <code>public.co_sucursal</code> table reference
     */
    public CoSucursal(String alias) {
        this(DSL.name(alias), CO_SUCURSAL);
    }

    /**
     * Create an aliased <code>public.co_sucursal</code> table reference
     */
    public CoSucursal(Name alias) {
        this(alias, CO_SUCURSAL);
    }

    private CoSucursal(Name alias, Table<CoSucursalRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoSucursal(Name alias, Table<CoSucursalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CoSucursal(Table<O> child, ForeignKey<O, CoSucursalRecord> key) {
        super(child, key, CO_SUCURSAL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CO_SUCURSAL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CoSucursalRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CO_SUCURSAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CoSucursalRecord> getPrimaryKey() {
        return Keys.CO_SUCURSAL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoSucursalRecord>> getKeys() {
        return Arrays.<UniqueKey<CoSucursalRecord>>asList(Keys.CO_SUCURSAL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursal as(String alias) {
        return new CoSucursal(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoSucursal as(Name alias) {
        return new CoSucursal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoSucursal rename(String name) {
        return new CoSucursal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoSucursal rename(Name name) {
        return new CoSucursal(name, null);
    }
}
