/*
 * This file is generated by jOOQ.
 */
package com.api.jooq.tables;


import com.api.jooq.Indexes;
import com.api.jooq.Keys;
import com.api.jooq.Public;
import com.api.jooq.tables.records.UsuarioRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuario extends TableImpl<UsuarioRecord> {

    private static final long serialVersionUID = 1991216718;

    /**
     * The reference instance of <code>public.usuario</code>
     */
    public static final Usuario USUARIO = new Usuario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsuarioRecord> getRecordType() {
        return UsuarioRecord.class;
    }

    /**
     * The column <code>public.usuario.id</code>.
     */
    public final TableField<UsuarioRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('usuario_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.usuario.nombre</code>.
     */
    public final TableField<UsuarioRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.usuario.correo</code>.
     */
    public final TableField<UsuarioRecord, String> CORREO = createField("correo", org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>public.usuario.password</code>.
     */
    public final TableField<UsuarioRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>public.usuario.fecha_genero</code>.
     */
    public final TableField<UsuarioRecord, Timestamp> FECHA_GENERO = createField("fecha_genero", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.usuario.fecha_modifico</code>.
     */
    public final TableField<UsuarioRecord, Timestamp> FECHA_MODIFICO = createField("fecha_modifico", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.usuario.genero</code>.
     */
    public final TableField<UsuarioRecord, Integer> GENERO = createField("genero", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.usuario.modifico</code>.
     */
    public final TableField<UsuarioRecord, Integer> MODIFICO = createField("modifico", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.usuario.eliminado</code>.
     */
    public final TableField<UsuarioRecord, Boolean> ELIMINADO = createField("eliminado", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.usuario</code> table reference
     */
    public Usuario() {
        this(DSL.name("usuario"), null);
    }

    /**
     * Create an aliased <code>public.usuario</code> table reference
     */
    public Usuario(String alias) {
        this(DSL.name(alias), USUARIO);
    }

    /**
     * Create an aliased <code>public.usuario</code> table reference
     */
    public Usuario(Name alias) {
        this(alias, USUARIO);
    }

    private Usuario(Name alias, Table<UsuarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private Usuario(Name alias, Table<UsuarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Usuario(Table<O> child, ForeignKey<O, UsuarioRecord> key) {
        super(child, key, USUARIO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USUARIO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UsuarioRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsuarioRecord> getPrimaryKey() {
        return Keys.USUARIO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsuarioRecord>> getKeys() {
        return Arrays.<UniqueKey<UsuarioRecord>>asList(Keys.USUARIO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuario as(String alias) {
        return new Usuario(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuario as(Name alias) {
        return new Usuario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuario rename(String name) {
        return new Usuario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuario rename(Name name) {
        return new Usuario(name, null);
    }
}
